DATA:
  TRAIN_IMG_DATA: "datasets/second_stage/swin_transformer_extract/train"
  VALID_IMG_DATA: "datasets/second_stage/swin_transformer_extract/valid"
  TEST_IMG_DATA: "datasets/second_stage/swin_transformer_extract/test"
DATA_LOADER:
  NAME: "second_stage_data"
  SECOND_STAGE:
    METHOD: "spectrum"
    TYPE: "pred"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 0
MODEL:
  NAME: "spectrum_conv_model2"
  SPECTRUM_CHANNEL: 5
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.2
  MILESTONE: [40,]
TRAIN:
  TRAINER: "SpectrumTrainer"
  MAX_EPOCH: 100
  OUTPUT_DIR: "results_second_stage/spectrum_on_pred/10_swin_spectrum"
