DATA:
  TRAIN_IMG_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/train_3_face"
  VALID_IMG_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/valid_3_face"
  TEST_IMG_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/test_3_face"
  TRAIN_LABEL_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/annotation_3/annotation_train_3.pkl"
  VALID_LABEL_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/annotation_3/annotation_valid_3.pkl"
  TEST_LABEL_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/annotation_3/annotation_test_3.pkl"
DATA_LOADER:
  NAME: "single_frame_data_loader"
  TRANSFORM: "face_image_x2_transform"
  TRAIN_BATCH_SIZE: 32
  NUM_WORKERS: 4
  
SOLVER:
  LR_INIT: 0.01
MODEL:
  NAME: "hr_net_model"
  WEIGHT_PATH: "/scratch/yw8988/DeepPersonality-main/pre_trained_weights/hrnetv2_w18_imagenet_pretrained.pth"
TRAIN:
  OUTPUT_DIR: "results/unified_face_images/MOSE_HRNet_Alia_face_Pretrained"
