DATA:
  ROOT: "datasets"
  TRAIN_IMG_DATA: "ChaLearn2016_tiny/train_data"
  VALID_IMG_DATA: "ChaLearn2016_tiny/valid_data"
  TEST_IMG_DATA: "ChaLearn2016_tiny/test_data"
  TRAIN_AUD_DATA: "ChaLearn2016_tiny/voice_data/voice_librosa/train_data"
  VALID_AUD_DATA: "ChaLearn2016_tiny/voice_data/voice_librosa/valid_data"
  TEST_AUD_DATA: "ChaLearn2016_tiny/voice_data/voice_librosa/test_data"
  TRAIN_LABEL_DATA: "ChaLearn2016_tiny/annotation/annotation_training.pkl"
  VALID_LABEL_DATA: "ChaLearn2016_tiny/annotation/annotation_validation.pkl"
  TEST_LABEL_DATA: "ChaLearn2016_tiny/annotation/annotation_test.pkl"
DATA_LOADER:
  NAME: "bimodal_resnet_data_loader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 8
  VALID_BATCH_SIZE: 4
  NUM_WORKERS: 0
MODEL:
  NAME: "audiovisual_resnet"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [100, 200]
TRAIN:
  TRAINER: "BiModalTrainer"
  MAX_EPOCH: 30
  OUTPUT_DIR: "results/demo/unified_frame_images/03_bimodal_resnet"
