DATA:
  TRAIN_LABEL_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/ChaLearn2016_tiny/annotation/annotation_training.pkl"
  VALID_LABEL_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/ChaLearn2016_tiny/annotation/annotation_validation.pkl"
  TEST_LABEL_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/ChaLearn2016_tiny/annotation/annotation_testing.pkl"
  TRAIN_IMG_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/ChaLearn2016_tiny/train_data"
  VALID_IMG_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/ChaLearn2016_tiny/valid_data"
  TEST_IMG_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/ChaLearn2016_tiny/test_data"
DATA_LOADER:
  NAME: "vat_data_loader"
  TRANSFORM: "set_vat_transform_op"
  TRAIN_BATCH_SIZE: 4
MODEL:
  NAME: "vat_model"
TRAIN:
  OUTPUT_DIR: "results/unified_frame_images/14_vat"
