DATA:
  TRAIN_LABEL_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/new_annotation/annotation_train_2.pkl"
  VALID_LABEL_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/new_annotation/annotation_valid_2.pkl"
  TEST_LABEL_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/new_annotation/annotation_test_2.pkl"
  TRAIN_IMG_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/new_train_data"
  VALID_IMG_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/new_valid_data"
  TEST_IMG_DATA: "/scratch/yw8988/DeepPersonality-main/datasets/MOSE/new_test_data"
DATA_LOADER:
  TRAIN_BATCH_SIZE: 24
MODEL:
  NAME: "swin_transformer_model"
  WEIGHT_PATH: "/scratch/yw8988/DeepPersonality-main/pre_trained_weights/swin_small_patch4_window7_224.pth"
SOLVER:
  LR_INIT: 0.001
TRAIN:
  MAX_EPOCH: 30
  OUTPUT_DIR: "results/unified_frame_images/MOSE_10_swin_transformer_Alia_test"
