DATA:
  TRAIN_LABEL_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/MOSE/annotation/annotation_train.pkl"
  VALID_LABEL_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/MOSE/annotation/annotation_valid.pkl"
  TEST_LABEL_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/MOSE/annotation/annotation_test.pkl"
  TRAIN_IMG_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/MOSE/train_data"
  VALID_IMG_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/MOSE/valid_data"
  TEST_IMG_DATA: "/scratch/jl10897/DeepPersonality-main/datasets/MOSE/test_data"

MODEL:
  NAME: "se_resnet50"
TRAIN:
  MAX_EPOCH: 30
  OUTPUT_DIR: "results/unified_frame_images/MOSE_08_senet"
