DATA:
  TRAIN_IMG_DATA: "datasets/second_stage/deep_bimodal_reg_extract/train"
  VALID_IMG_DATA: "datasets/second_stage/deep_bimodal_reg_extract/valid"
  TEST_IMG_DATA: "datasets/second_stage/deep_bimodal_reg_extract/test"
DATA_LOADER:
  NAME: "second_stage_data"
  SECOND_STAGE:
    METHOD: "statistic"
    TYPE: "pred"
  TRAIN_BATCH_SIZE: 64
  NUM_WORKERS: 0
MODEL:
  NAME: "statistic_mlp"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.01
  MILESTONE: [100]
TRAIN:
  TRAINER: "StatisticTrainer"
  MAX_EPOCH: 200
  OUTPUT_DIR: "results_second_stage/statistic/01_deep_bimodal_statistic"
