DATA:
  ROOT: "datasets/chalearn2021"
  SESSION: "animal"
  TYPE: "frame"
DATA_LOADER:
  NAME: "true_per_slow_fast_data_loader"
  TRANSFORM: "standard_frame_transform"
  TRAIN_BATCH_SIZE: 1
  NUM_WORKERS: 8
MODEL:
  NAME: "slow_fast_model"
LOSS:
  NAME: "mean_square_error"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [15, 18]
TRAIN:
  TRAINER: "ImageListTrainer"
  MAX_EPOCH: 100
  LOG_INTERVAL: 10
  OUTPUT_DIR: "results_true_personality/unified_frame_images_animal/05_slow_fast_video_level"
